phpbb:
  image: bitnami/phpbb:latest
  environment:
    ALLOW_EMPTY_PASSWORD=yes
    PHPBB_DATABASE_USER=bn_phpbb
    PHPBB_DATABASE_PASSWORD=bitnami
    PHPBB_DATABASE_NAME=bitnami_phpbb
  links:
    - db:mysql
  ports:
    - "4000:8080"

db:
  image: bitnami/mariadb:latest
  environment:
    ALLOW_EMPTY_PASSWORD=yes    
    MARIADB_USER=bn_phpbb
    MARIADB_PASSWORD=bitnami
    MARIADB_DATABASE=bitnami_phpbb
